### ISSUE TITLE
更新“被冰箱冻结的”app后无法打开

### ISSUE THREAD

**Issue by karttv** [heruoxin/Ice-Box-Docs#2]
1.冰箱冻结工商银行app后，从冰冻列表里直接点击打开工商银行app，该软件提示更新，然后下载更新安装之后，打不开。
2.尝试解冻工商银行app后，仍然打不开
3.卸载已经解冻的工行app，然后重启手机再次安装工商银行app依旧打不开，求解！！！谢谢！

**Comment by heruoxin** [comment]
你好，很抱歉，不清楚如何解决该问题。如有其他问题请使用应用内反馈功能联系
